spring.datasource.url=jdbc:mysql://localhost:3306/online_book_store?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Acid-33134
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.servlet.context-path=/api
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

